apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: tf-jx-charmed-tuna
    devEnvApprovers:
    - todo
    environmentGitOwner: todo
    gitKind: github
    gitName: github
    gitServer: https://github.com
    project: "927310973816"
    provider: eks
    region: us-west-2
    registry: 927310973816.dkr.ecr.us-west-2.amazonaws.com
  environments:
  - key: dev
    owner: GhettoLabs
    repository: jx3-eks-vault
  - key: staging
  - key: production
  ingress:
    domain: 52.40.2.249.nip.io
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: james-knott
  repository: nexus
  secretStorage: vault
  storage:
  - name: logs
    url: s3://logs-tf-jx-charmed-tuna-20211021103857699400000007
  - name: reports
    url: s3://reports-tf-jx-charmed-tuna-20211021103857699300000006
  - name: repository
    url: s3://repository-tf-jx-charmed-tuna-20211021103857699200000005
  terraform: true
  vault:
    aws:
      dynamoDBRegion: us-west-2
      dynamoDBTable: vault-unseal-tf-jx-charmed-tuna-mlUNFX6u
      iamUserName: jenkinsx
      kmsKeyId: 18d6be57-de56-4c7e-8370-fc826f6901bd
      kmsRegion: us-west-2
      s3Bucket: vault-unseal-tf-jx-charmed-tuna-20211021103858386200000008
      s3Region: us-west-2
  webhook: lighthouse
